### ISSUE TITLE
Import quote data

### ISSUE THREAD

**Issue by jjw123** [quoter/quoter#339]
**Is your feature request related to a problem? Please describe.**
Our server has hundreds or thousands of quotes from before the bot was added and i'd like an easy way to import them into the bot without having to type one at a time. The right click add isn't ideal as the quotes are all new messages in the format of "{quote}" - {author} it would also lose the quoter

**Describe the solution you'd like**
A new command that will take a JSON file in the same format as the export, with the additional parameter of the quoter which will add all the quotes in the json

**Describe alternatives you've considered**
A new option on right click that will allow old quotes in the format mentioned above to be added

**Comment by n1ckoates** [comment]
I've started working on this, it should be in the next release (v5.1.0) of Quoter.

**Comment by n1ckoates** [comment]
Quoter v5.1.0 has been released, and this command is now available!
