### ISSUE TITLE
More Max Quotes

### ISSUE THREAD

**Issue by F1reb0y** [quoter/quoter#382]
**Is your feature request related to a problem? Please describe.**
I would like to be able to quote more things
**Describe the solution you'd like**
up the maxguildquotes to a much larger number, around 1000-2000
**Describe alternatives you've considered**

**Additional context**

**Comment by n1ckoates** [comment]
For the official version of Quoter, the default maximum of 150 can be raised upon request. Please ask in the [Quoter support server](https://discord.gg/QzXTgS2CNk) and include your server ID. The maximum will likely be raised in the future after I improve performance with large sets of quotes.

For self hosters, the default max can be raised by changing the associated options in `config.json`, or by changing it per-guild in the database.
